.PHONY: final_project

CXXFLAGS = -isystem /usr/include/eigen3/ -std=c++17 -g -O3 -DNDEBUG -march=native -Wall -Wextra

final_project: final_project.cpp
	g++ $(CXXFLAGS) final_project.cpp -o final_project

